paulinedussart/coworkspace

app/controllers/reservations_controller.rb, app/controllers/reviews_controller.rb, app/controllers/spaces_controller.rb, test/controllers/reservations_controller_test.rb, test/controllers/reviews_controller_test.rb, test/controllers/spaces_controller_test.rb
creation des 3 controllers : 
- reviews
- spaces
- reservations
=> creation controller ok

app/models/desk.rb, app/models/owner.rb, app/models/service.rb, app/models/space.rb, app/models/space_service.rb, app/models/user.rb, db/migrate/20190604084119_create_services.rb, db/migrate/20190604084200_create_space_services.rb, db/schema.rb, test/models/service_test.rb, test/models/space_service_test.rb
Creation Model
- Services 
- SpaceServices 
Add Association to model
TODO: Validations
=> creation model services

app/assets/stylesheets/pages/_form.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/spaces_controller.rb, app/views/spaces/new.html.erb, config/routes.rb, db/seeds.rb
Create Services#new
seed des services
=> create services controller

db/seeds.rb
ajout de website, adresses, name, etc . User & Spaces.
=> ajout de seeds

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_map.scss, app/controllers/spaces_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/space.rb, app/views/layouts/application.html.erb, app/views/spaces/index.html.erb, config/initializers/geocoder.rb, config/routes.rb, db/migrate/20190604095953_add_coordinates_to_spaces.rb, db/schema.rb, package.json, yarn.lock
-Add gem geocoder
- create js files
- create index.html.reb in spaces_controller
=> Mapbox and geocoder

app/views/spaces/index.html.erb, db/schema.rb, db/seeds.rb
=> modification des seeds

app/assets/stylesheets/pages/_form.scss, app/controllers/spaces_controller.rb, app/javascript/packs/application.js, app/javascript/packs/service_choice.js, app/views/spaces/new.html.erb, config/routes.rb, db/seeds.rb
Owners_spaces#new 
- creation form-spaces new
- insert JS when click on checkboxes
TODO: Rajouter lien entre spaces et desk (spaces has many desks - il doit renseigner le nombre de desk)
=> form-space done without css grid

app/assets/stylesheets/components/_index.scss, app/controllers/spaces_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/views/shared/_infowindow.html.erb, app/views/spaces/index.html.erb, app/views/spaces/show.html.erb, db/seeds.rb, package.json, yarn.lock
- creation index et show ok 
doit être encore developper 
Seeds à completer
=> Creation index/show view and action

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/javascript/plugins/init_mapbox.js, app/views/shared/_infowindow.html.erb, app/views/spaces/index.html.erb, app/views/spaces/show.html.erb, db/seeds.rb
=> Spaces index show

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/models/space.rb, app/uploaders/photo_uploader.rb, app/views/spaces/index.html.erb, app/views/spaces/new.html.erb, config/routes.rb, db/seeds.rb
Cloudinary et carriewave set-up done 
- mis en place sur Spaces#index avec le cl-image-tag
=> Add cloudinary carrierwave

app/assets/stylesheets/components/_card.scss, app/views/spaces/index.html.erb, db/seeds.rb
Cloudinary test with seed and  spaces#index
some CSS left to do
=> cloudinary index almost done with CSS

.gitignore, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
la nav bar change suivant le statut du user et suivant les pages 
A voir comment on fait pour le owner
=> navbar de co, change suivant les pages

.gitignore, db/schema.rb, db/seeds.rb
Modifications : 
- des photos identiques
- des adresses non fonctionnelles qui ne s'affichent pas
- adresse pour les 2 desks à afficher à ManlyBeach 
Ajouts : 
- nombre de desk pour Havana Beach
- nombre de desk pour Work-in
=> Seed check

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/application_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
=> Signup form

.gitignore, app/models/space.rb, app/views/spaces/show.html.erb
show + modal (résa details avant book)
=> Show spaces

app/models/space.rb, public/404.html, public/422.html, public/500.html
design des pages 404 422 et 500 à la charte du site :)
=> Essai messagerie

app/assets/stylesheets/pages/_home.scss, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/pages/home.html.erb, package.json, yarn.lock
date pickr to choose dates 
See to change CSS
=> date pickr implemented

db/schema.rb, db/seeds.rb
reviews créées & desk Australia créés & new users créés
=> Modif autralia

db/seeds.rb
@aurelie131313 - les seeds sont maintenant ok 
- il y a pas besoin de mettre les created_at et updated_at, c'est automatique
- rating devait être un integer et non une string
- les users et spaces devaient être les noms de variables (comme pour Desk.create) et non des strings
--> on a du checker pour pouvoir bosser dessus ce soir, sinon ça plantait le rails db:seed
=> seed reviews check ok

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/spaces_controller.rb, app/views/spaces/show.html.erb
- manque les horaires, les services, le prix, la photo
=> spaces-show-v1

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/views/owners/registrations/new.html.erb, app/views/owners/sessions/new.html.erb, app/views/pages/home.html.erb, app/views/spaces/index.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb
le login est fait pour les types de users depuis la homepage
=> login depuis homepage pour user et company

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_show.scss, app/views/spaces/index.html.erb, app/views/spaces/show.html.erb
methode average reviews ok
- affichage dans index et show
=> methode average reviews done

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_message.scss, app/views/chat_rooms/show.html.erb, db/seeds.rb
=> Beaute msg

app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/reservations_controller.rb, app/controllers/spaces_controller.rb, app/javascript/packs/application.js, app/javascript/packs/book_reservation.js, app/views/reviews/_show.html.erb, app/views/spaces/show.html.erb, config/routes.rb, db/migrate/20190609132306_add_total_price_to_reservation.rb, db/schema.rb, db/seeds.rb
- modal reviews
- JS pour book a desk
=> Book show spaces

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form.scss, app/javascript/packs/book_reservation.js, app/views/spaces/show.html.erb
- design  create resa form
- modification des dollars Australiens
- Mise en page des amenities
=> form resa et $

app/assets/stylesheets/pages/_dashboard.scss, app/controllers/owner/base_controller.rb, app/controllers/owner/reservations_controller.rb, app/views/layouts/ownersession.html.erb, app/views/owner/reservations/index.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb
méthodes pour changer le statut d'une résa coté owner. 
A TESTER sur heroku pour voir si le changement se fait bien sur les deux côtés
=> update reservation's status

public/422.html, public/500.html
=> Creapageerror

Gemfile, app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/views/owners/sessions/new.html.erb, app/views/pages/dashboard.html.erb
=> Petites corrections

app/assets/stylesheets/components/_button.scss, app/controllers/reservations_controller.rb, app/models/reservation.rb, app/views/reservations/paiement.html.erb, app/views/spaces/show.html.erb
=> fix pay button
